### ISSUE TITLE
404 redirection

### ISSUE THREAD

**Issue by syarul** [Cmdv/cycle-webpack-boilerplate#22]
I've noticed the 404 redirection only happen when the string is actual extension of ```page1``` or ```page2```, which mean 404 redirection triggered when you write the url ```../page1xx``` but writing e.g ```../page``` will redirect to index.html. Possible bug in @cycle/history. Are you aware of this @Cmdv ?

**Comment by Cmdv** [comment]
umm I was unaware of this is it a case that `/randomUrl` will not take you to a random URL? I know there are issues with the git pages not playing nice with the router but I'll have a look at the local version see if I can see an issue. I have a feeling it is fixed in the branch `cyclic-router` but will double check

**Comment by Cmdv** [comment]
@syarul right turns out there is an issue with switch-path handling both `*` + `/` so just going to do a PR and that should sort it out 👍

**Comment by syarul** [comment]
great!
